import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import "@rainbow-me/rainbowkit/styles.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import Notifications from "@/components/Notifications";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Providers>
          <div className="min-h-screen flex flex-col">
            <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-md dark:bg-gray-900/80 border-b border-gray-200 dark:border-gray-800 shadow-sm">
              <Navbar />
            </header>
            <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-10">
              {children}
            </main>
            <footer className="bg-gray-50 dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800 py-8">
              <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex flex-col items-center justify-center">
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    &copy; {new Date().getFullYear()} Student Visa System. All rights reserved.
                  </p>
                  <div className="mt-2 flex space-x-4">
                    <a href="#" className="text-gray-500 hover:text-primary dark:text-gray-400 dark:hover:text-primary-foreground">
                      Terms of Service
                    </a>
                    <a href="#" className="text-gray-500 hover:text-primary dark:text-gray-400 dark:hover:text-primary-foreground">
                      Privacy Policy
                    </a>
                  </div>
                </div>
              </div>
            </footer>
          </div>
          <Notifications />
        </Providers>
      </body>
    </html>
  );
}
